In [2]:
import pandas as pd
import numpy as np

In [3]:
serie1 = pd.Series(["Paolo","Luca","Pietro","Matteo"])
print(serie1)

serie2 = pd.Series(
    [8, 7.5, 6, 10],
    index=["Matteo", "Luca", "Franco", "Mattia"]
)

print(serie2)

corretti = serie2 +1.5
print(corretti)

0     Paolo
1      Luca
2    Pietro
3    Matteo
dtype: str
Matteo     8.0
Luca       7.5
Franco     6.0
Mattia    10.0
dtype: float64
Matteo     9.5
Luca       9.0
Franco     7.5
Mattia    11.5
dtype: float64

In [4]:
dati = {
    'nome':        ['Alice', 'Bruno', 'Carla', 'Davide', 'Elena',
                    'Franco', 'Giulia', 'Hasan', 'Irene', 'Luca',
                    'Maria', 'Nicola'],
    'classe':      ['4A', '4A', '4B', '4B', '4A',
                    '4C', '4C', '4B', '4A', '4C',
                    '4B', '4C'],
    'sesso':       ['F', 'M', 'F', 'M', 'F',
                    'M', 'F', 'M', 'F', 'M',
                    'F', 'M'],
    'eta':         [17, 18, 17, 18, 17, 18, 17, 18, 17, 18, 17, 18],
    'matematica':  [8, 6, 9, 7, 8, 5, 9, 7, 6, 8, 7, 6],
    'italiano':    [7, 8, 6, 7, 9, 8, 7, 6, 8, 7, 8, 9],
    'informatica': [9, 7, 8, 9, 7, 6, 9, 8, 7, 9, 8, 7],
    'fisica':      [8, 6, 7, 8, 7, 5, 8, 7, 6, 7, 7, 6],
    'storia':      [7, 9, 8, 6, 8, 9, 7, 7, 9, 8, 7, 8]
}

dataframe = pd.DataFrame(dati)
print(dataframe.info())
dataframe.describe()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nome         12 non-null     str
 1   classe       12 non-null     str
 2   sesso        12 non-null     str
 3   eta          12 non-null     int64
 4   matematica   12 non-null     int64
 5   italiano     12 non-null     int64
 6   informatica  12 non-null     int64
 7   fisica       12 non-null     int64
 8   storia       12 non-null     int64
dtypes: int64(6), str(3)
memory usage: 996.0 bytes
None

             eta  matematica  italiano  informatica     fisica     storia
count  12.000000   12.000000      12.0    12.000000  12.000000  12.000000
mean   17.500000    7.166667       7.5     7.833333   6.833333   7.750000
std     0.522233    1.267304       1.0     1.029857   0.937437   0.965307
min    17.000000    5.000000       6.0     6.000000   5.000000   6.000000
25%    17.000000    6.000000       7.0     7.000000   6.000000   7.000000
50%    17.500000    7.000000       7.5     8.000000   7.000000   8.000000
75%    18.000000    8.000000       8.0     9.000000   7.250000   8.250000
max    18.000000    9.000000       9.0     9.000000   8.000000   9.000000

In [5]:
dataframe.head(5)

     nome classe sesso  eta  matematica  italiano  informatica  fisica  storia
0   Alice     4A     F   17           8         7            9       8       7
1   Bruno     4A     M   18           6         8            7       6       9
2   Carla     4B     F   17           9         6            8       7       8
3  Davide     4B     M   18           7         7            9       8       6
4   Elena     4A     F   17           8         9            7       7       8

In [6]:
dataframe.tail(5)

,nome,classe,sesso,eta,matematica,italiano,informatica,fisica,storia
7,Hasan,4B,M,18,7,6,8,7,7
8,Irene,4A,F,17,6,8,7,6,9
9,Luca,4C,M,18,8,7,9,7,8
10,Maria,4B,F,17,7,8,8,7,7
11,Nicola,4C,M,18,6,9,7,6,8

In [7]:
dimensioni = dataframe.shape
nrRighe, nrColone = dataframe.shape
print(f"Il dataframe ha {nrRighe} righe e {nrColone} colonne.")
dataframe.to_csv("voti.csv", index=False)

Il dataframe ha 12 righe e 9 colonne.

In [8]:
dfDaCSV = pd.read_csv('voti.csv')
dfDaCSV.head(5)

     nome classe sesso  eta  matematica  italiano  informatica  fisica  storia
0   Alice     4A     F   17           8         7            9       8       7
1   Bruno     4A     M   18           6         8            7       6       9
2   Carla     4B     F   17           9         6            8       7       8
3  Davide     4B     M   18           7         7            9       8       6
4   Elena     4A     F   17           8         9            7       7       8

In [9]:
voti_mat = dfDaCSV['matematica']
voti_mat.info()

<class 'pandas.Series'>
RangeIndex: 12 entries, 0 to 11
Series name: matematica
Non-Null Count  Dtype
--------------  -----
12 non-null     int64
dtypes: int64(1)
memory usage: 228.0 bytes

In [10]:
solo_voti = dfDaCSV[['matematica', 'italiano', 'informatica']]
solo_voti.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   matematica   12 non-null     int64
 1   italiano     12 non-null     int64
 2   informatica  12 non-null     int64
dtypes: int64(3)
memory usage: 420.0 bytes

In [11]:
prima_riga = dfDaCSV.iloc[0]
ultima_riga = dfDaCSV.iloc[-1]
range_righe = dfDaCSV.iloc[2:5]
range_righe_colonne = dfDaCSV.iloc[0:4, 4:9]

solo_una_riga = range_righe_colonne.loc[0]
solo_una_riga

solo_mate_info = range_righe_colonne.loc[0:2, ['matematica', 'informatica']]
solo_mate_info

   matematica  informatica
0           8            9
1           6            7
2           9            8

In [12]:
bravi_mate = dfDaCSV[dfDaCSV['matematica'] >= 8]
bravi_mate
bravi_stem = dfDaCSV[(dfDaCSV['matematica'] >= 8) & (dfDaCSV['informatica'] >= 8)]
bravi_stem

studenti_4A = dfDaCSV[dfDaCSV['classe'] == '4A']
studenti_4A

studenti_altre_classi = dfDaCSV[dfDaCSV['classe'].isin(['4B', '4C'])]
studenti_altre_classi

studenti_altre_classi_2 = dfDaCSV[~dfDaCSV['classe'].isin(['4A'])]
studenti_altre_classi_2

,nome,classe,sesso,eta,matematica,italiano,informatica,fisica,storia
2,Carla,4B,F,17,9,6,8,7,8
3,Davide,4B,M,18,7,7,9,8,6
5,Franco,4C,M,18,5,8,6,5,9
6,Giulia,4C,F,17,9,7,9,8,7
7,Hasan,4B,M,18,7,6,8,7,7
9,Luca,4C,M,18,8,7,9,7,8
10,Maria,4B,F,17,7,8,8,7,7
11,Nicola,4C,M,18,6,9,7,6,8

In [13]:
lista_materie = ['matematica','italiano','informatica','fisica','storia']
dfDaCSV['media'] = dfDaCSV[lista_materie].mean(axis=1).round(2)

dfDaCSV['media_scien'] = dfDaCSV[['matematica','informatica','fisica']].mean(axis=1).round(2)
dfDaCSV['media_uma'] = dfDaCSV[['italiano','storia']].mean(axis=1).round(2)

dfDaCSV

,nome,classe,sesso,eta,matematica,italiano,informatica,fisica,storia,media,media_scien,media_uma
0,Alice,4A,F,17,8,7,9,8,7,7.8,8.33,7.0
1,Bruno,4A,M,18,6,8,7,6,9,7.2,6.33,8.5
2,Carla,4B,F,17,9,6,8,7,8,7.6,8.00,7.0
3,Davide,4B,M,18,7,7,9,8,6,7.4,8.00,6.5
4,Elena,4A,F,17,8,9,7,7,8,7.8,7.33,8.5
5,Franco,4C,M,18,5,8,6,5,9,6.6,5.33,8.5
6,Giulia,4C,F,17,9,7,9,8,7,8.0,8.67,7.0
7,Hasan,4B,M,18,7,6,8,7,7,7.0,7.33,6.5
8,Irene,4A,F,17,6,8,7,6,9,7.2,6.33,8.5
9,Luca,4C,M,18,8,7,9,7,8,7.8,8.00,7.5
10,Maria,4B,F,17,7,8,8,7,7,7.4,7.33,7.5
11,Nicola,4C,M,18,6,9,7,6,8,7.2,6.33,8.5

In [14]:
nuovo_dfDaCSV_rinominato = dfDaCSV.rename(columns={
    'media': 'media_totale'
})

nuovo_dfDaCSV_rinominato

,nome,classe,sesso,eta,matematica,italiano,informatica,fisica,storia,media_totale,media_scien,media_uma
0,Alice,4A,F,17,8,7,9,8,7,7.8,8.33,7.0
1,Bruno,4A,M,18,6,8,7,6,9,7.2,6.33,8.5
2,Carla,4B,F,17,9,6,8,7,8,7.6,8.00,7.0
3,Davide,4B,M,18,7,7,9,8,6,7.4,8.00,6.5
4,Elena,4A,F,17,8,9,7,7,8,7.8,7.33,8.5
5,Franco,4C,M,18,5,8,6,5,9,6.6,5.33,8.5
6,Giulia,4C,F,17,9,7,9,8,7,8.0,8.67,7.0
7,Hasan,4B,M,18,7,6,8,7,7,7.0,7.33,6.5
8,Irene,4A,F,17,6,8,7,6,9,7.2,6.33,8.5
9,Luca,4C,M,18,8,7,9,7,8,7.8,8.00,7.5
10,Maria,4B,F,17,7,8,8,7,7,7.4,7.33,7.5
11,Nicola,4C,M,18,6,9,7,6,8,7.2,6.33,8.5

In [15]:
df_ordinato = nuovo_dfDaCSV_rinominato.sort_values('media_totale', ascending=False)
df_ordinato

,nome,classe,sesso,eta,matematica,italiano,informatica,fisica,storia,media_totale,media_scien,media_uma
6,Giulia,4C,F,17,9,7,9,8,7,8.0,8.67,7.0
0,Alice,4A,F,17,8,7,9,8,7,7.8,8.33,7.0
4,Elena,4A,F,17,8,9,7,7,8,7.8,7.33,8.5
9,Luca,4C,M,18,8,7,9,7,8,7.8,8.00,7.5
2,Carla,4B,F,17,9,6,8,7,8,7.6,8.00,7.0
3,Davide,4B,M,18,7,7,9,8,6,7.4,8.00,6.5
10,Maria,4B,F,17,7,8,8,7,7,7.4,7.33,7.5
1,Bruno,4A,M,18,6,8,7,6,9,7.2,6.33,8.5
8,Irene,4A,F,17,6,8,7,6,9,7.2,6.33,8.5
11,Nicola,4C,M,18,6,9,7,6,8,7.2,6.33,8.5
7,Hasan,4B,M,18,7,6,8,7,7,7.0,7.33,6.5
5,Franco,4C,M,18,5,8,6,5,9,6.6,5.33,8.5

In [26]:
dfDaCSV['totale'] = dfDaCSV[['matematica', 'italiano', 'informatica', 'fisica', 'storia']].sum(axis=1)
dfDaCSV.drop(columns=['totale'], inplace=True)
dfDaCSV.dtypes

dfDaCSV['classe'].value_counts()
dfDaCSV['classe'].value_counts(normalize=True).round(2) * 100

dfDaCSV['sesso'].unique()
dfDaCSV['sesso'].nunique()

2

In [36]:
dfConVuoti = dfDaCSV.copy()
dfConVuoti.loc[2, 'matematica'] = np.nan
dfConVuoti.loc[4, 'storia'] = np.nan
dfConVuoti.loc[6, 'fisica'] = np.nan
dfConVuoti.loc[7, 'fisica'] = np.nan
dfConVuoti.loc[10, 'italiano'] = np.nan
dfConVuoti.info()
dfConVuoti.isnull().sum()

dfConVuoti['matematica'] = dfConVuoti['matematica'].fillna(dfConVuoti['matematica'].mean())
dfConVuoti

dfSenzaRighe = dfConVuoti.dropna()
dfSenzaRighe

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nome         12 non-null     str
 1   classe       12 non-null     str
 2   sesso        12 non-null     str
 3   eta          12 non-null     int64
 4   matematica   11 non-null     float64
 5   italiano     11 non-null     float64
 6   informatica  12 non-null     int64
 7   fisica       10 non-null     float64
 8   storia       11 non-null     float64
 9   media        12 non-null     float64
 10  media_scien  12 non-null     float64
 11  media_uma    12 non-null     float64
dtypes: float64(7), int64(2), str(3)
memory usage: 1.3 KB

,nome,classe,sesso,eta,matematica,italiano,informatica,fisica,storia,media,media_scien,media_uma
0,Alice,4A,F,17,8.0,7.0,9,8.0,7.0,7.8,8.33,7.0
1,Bruno,4A,M,18,6.0,8.0,7,6.0,9.0,7.2,6.33,8.5
2,Carla,4B,F,17,7.0,6.0,8,7.0,8.0,7.6,8.00,7.0
3,Davide,4B,M,18,7.0,7.0,9,8.0,6.0,7.4,8.00,6.5
5,Franco,4C,M,18,5.0,8.0,6,5.0,9.0,6.6,5.33,8.5
8,Irene,4A,F,17,6.0,8.0,7,6.0,9.0,7.2,6.33,8.5
9,Luca,4C,M,18,8.0,7.0,9,7.0,8.0,7.8,8.00,7.5
11,Nicola,4C,M,18,6.0,9.0,7,6.0,8.0,7.2,6.33,8.5